version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_USER
      - MONGODB_PASS
      - MONGODB_HOST=mongo
      - MONGODB_PORT
      - MQTT_HOST
      - MQTT_PORT
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - ${MQTT_HOST_PORT}:1883
